# Generated by Django 4.1.2 on 2023-01-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_create_at_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.TextField(default='No content'),
        ),
    ]
